Team3 participation session
Allegheny-Computer-Science-203-S2020/cs203-S2020-conduct pull request #10
Opened 2020-01-21 15:06 UTC by liux2

This Pull Request adds the content needed for the participation section of the conduct guide.

2020-01-21 19:26 UTC, enpuyou requested changes

2020-01-21 19:26 UTC, enpuyou commented on conduct.md
> +    * Must contribute when designated to, in a timely manner
"shall must" seems awkward

2020-01-21 19:26 UTC, enpuyou commented on conduct.md
> +    * Quick to respond in Slack to clarify confusing issues or assist other colleagues
Maybe rephrase to "respond quickly"

2020-01-21 19:26 UTC, enpuyou commented on conduct.md
> +    * Everyone’s opinion must be considered
This line needs to be rephrased.

2020-01-21 19:26 UTC, enpuyou commented on conduct.md
> +    * Willing to meetup and work outside of class
Be willing to

2020-01-21 19:26 UTC, enpuyou commented on conduct.md
> +    * Open minded
Be open-minded

2020-01-21 19:26 UTC, enpuyou commented on conduct.md
> +    * No show in lab sessions without the consent of the professor
This section also should be rephrased as above. Each bullet point should connect to "Member shall not"

2020-01-21 19:46 UTC, lussierc commented on conduct.md
> +    * Must contribute when designated to, in a timely manner
I agree, I will change this @enpuyou.

2020-01-21 20:07 UTC, ibarrezueta approved these changes

2020-01-21 20:33 UTC, enpuyou approved these changes

2020-01-21 20:33 UTC, corlettim approved these changes

2020-01-21 20:52 UTC, gkapfham commented
Hi @liux2 this branch is out of date with the base branch. Can you or a member of your team please update this? Thanks!

2020-01-22 19:47 UTC, lussierc approved these changes
The content overall looks pretty good and the formatting is good. I am approving this PR.

2020-01-22 19:54 UTC, merged