communication section in conduct
Allegheny-Computer-Science-203-S2020/cs203-S2020-conduct pull request #11
Opened 2020-01-21 20:22 UTC by hinckleyc

We finished Communication in the conduct.md file. 

Please let me know if we need to fix and errors.

2020-01-21 20:26 UTC, ibarrezueta submitted a review, later dismissed

2020-01-21 20:28 UTC, barrezuetai commented
conduct.md:15: MD005 Inconsistent indentation for list items at the same level
458conduct.md:18: MD005 Inconsistent indentation for list items at the same level
459conduct.md:23: MD012 Multiple consecutive blank lines

2020-01-21 20:53 UTC, gkapfham commented
Hello @hinckleyc, this branch is out of date with the master base branch. Can you or one of your eam members please update it? We cannot merge this into the master branch until everything is properly updated and the build is still passing correctly. Thanks!

2020-01-21 20:54 UTC, gkapfham commented
Hi @hinckleyc, please make sure that you assign four reviewers for this PR! We cannot merge the PRs until all four reviewers sign off on the content. Thanks!

2020-01-22 05:53 UTC, enpuyou requested changes
This PR is not up to standard as it does not conform to the conduct style guide

2020-01-28 19:25 UTC, gkapfham commented
Hi @hinckleyc, this branch has conflicts! Can you please resolve them today and ensure that this PR is merged if you have plans for it to be merged?

2020-01-28 20:00 UTC, koscinskic commented
Corrections and revisions are underway and should be resolved soon

2020-01-28 20:15 UTC, enpuyou requested changes

2020-01-28 20:15 UTC, enpuyou commented on conduct.md
You will also want to add a paragraph describing this sub-section

2020-01-28 21:01 UTC, tmgcassidy approved these changes
I have fixed all my Travis errors, and I have updated all outstanding formatting and content issues.

2020-01-28 21:01 UTC, koscinskic approved these changes

2020-01-28 21:03 UTC, stephensonc approved these changes

2020-01-28 21:04 UTC, enpuyou approved these changes

2020-01-28 21:06 UTC, merged